// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// History is the predicate function for history builders.
type History func(*sql.Selector)

// Meta is the predicate function for meta builders.
type Meta func(*sql.Selector)

// Progress is the predicate function for progress builders.
type Progress func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
