// Code generated by github.com/cshum/vipsgen from libvips 8.18.0; DO NOT EDIT.

#include <stdint.h>
#include <stdlib.h>
#include <vips/vips.h>

extern long long goSourceRead(uintptr_t, void *, long long);
extern long long goSourceSeek(uintptr_t, long long, int);
extern long long goTargetWrite(uintptr_t, void *, long long);
extern long long goTargetSeek(uintptr_t, long long, int);
extern void goHandleDelete(uintptr_t);

static gint64 go_read(VipsSourceCustom *source_custom, void *buffer, gint64 length, uintptr_t handle);
static gint64 go_source_seek(VipsSourceCustom *source_custom, gint64 offset, int whence, uintptr_t handle);
static gint64 go_write(VipsTargetCustom *target_custom, void *buffer, gint64 length, uintptr_t handle);
static gint64 go_target_seek(VipsTargetCustom *target_custom, gint64 offset, int whence, uintptr_t handle);
static void go_handle_weak_notify(gpointer data, GObject *where_the_object_was);

VipsSourceCustom * create_go_custom_source(uintptr_t handle);
VipsSourceCustom * create_go_custom_source_with_seek(uintptr_t handle);
VipsTargetCustom * create_go_custom_target(uintptr_t handle);
VipsTargetCustom * create_go_custom_target_with_seek(uintptr_t handle);

void clear_source(VipsSourceCustom **source_custom);
void clear_target(VipsTargetCustom **target_custom);
