// Code generated by github.com/cshum/vipsgen from libvips 8.18.0; DO NOT EDIT.

#include "connection.h"

static gint64 go_read(VipsSourceCustom *source_custom, void *buffer, gint64 length, uintptr_t handle)
{
  return goSourceRead(handle, buffer, length);
}

static gint64 go_source_seek(VipsSourceCustom *source_custom, gint64 offset, int whence, uintptr_t handle)
{
  return goSourceSeek(handle, offset, whence);
}

static gint64 go_write(VipsTargetCustom *target_custom, void *buffer, gint64 length, uintptr_t handle)
{
  return goTargetWrite(handle, buffer, length);
}

static gint64 go_target_seek(VipsTargetCustom *target_custom, gint64 offset, int whence, uintptr_t handle)
{
  return goTargetSeek(handle, offset, whence);
}

static void go_handle_weak_notify(gpointer data, GObject *where_the_object_was)
{
  goHandleDelete((uintptr_t) data);
}

VipsSourceCustom * create_go_custom_source(uintptr_t handle)
{
  VipsSourceCustom * source_custom = vips_source_custom_new();
  if (source_custom == NULL) return NULL;
  g_object_weak_ref(G_OBJECT(source_custom), go_handle_weak_notify, (gpointer) handle);
  g_signal_connect(source_custom, "read", G_CALLBACK(go_read), (gpointer) handle);
  return source_custom;
}

VipsSourceCustom * create_go_custom_source_with_seek(uintptr_t handle)
{
  VipsSourceCustom * source_custom = vips_source_custom_new();
  if (source_custom == NULL) return NULL;
  g_object_weak_ref(G_OBJECT(source_custom), go_handle_weak_notify, (gpointer) handle);
  g_signal_connect(source_custom, "read", G_CALLBACK(go_read), (gpointer) handle);
  g_signal_connect(source_custom, "seek", G_CALLBACK(go_source_seek), (gpointer) handle);
  return source_custom;
}

VipsTargetCustom * create_go_custom_target(uintptr_t handle)
{
  VipsTargetCustom * target_custom = vips_target_custom_new();
  if (target_custom == NULL) return NULL;
  g_object_weak_ref(G_OBJECT(target_custom), go_handle_weak_notify, (gpointer) handle);
  g_signal_connect(target_custom, "write", G_CALLBACK(go_write), (gpointer) handle);
  return target_custom;
}

VipsTargetCustom * create_go_custom_target_with_seek(uintptr_t handle)
{
  VipsTargetCustom * target_custom = vips_target_custom_new();
  if (target_custom == NULL) return NULL;
  g_object_weak_ref(G_OBJECT(target_custom), go_handle_weak_notify, (gpointer) handle);
  g_signal_connect(target_custom, "write", G_CALLBACK(go_write), (gpointer) handle);
  g_signal_connect(target_custom, "seek", G_CALLBACK(go_target_seek), (gpointer) handle);
  return target_custom;
}

void clear_source(VipsSourceCustom **source_custom) {
  if (G_IS_OBJECT(*source_custom)) g_clear_object(source_custom);
}

void clear_target(VipsTargetCustom **target_custom) {
  if (G_IS_OBJECT(*target_custom)) g_clear_object(target_custom);
}
