// Code generated by ent, DO NOT EDIT.

package meta

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the meta type in the database.
	Label = "meta"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldFavorite holds the string denoting the favorite field in the database.
	FieldFavorite = "favorite"
	// FieldFileIndices holds the string denoting the file_indices field in the database.
	FieldFileIndices = "file_indices"
	// FieldRead holds the string denoting the read field in the database.
	FieldRead = "read"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldHidden holds the string denoting the hidden field in the database.
	FieldHidden = "hidden"
	// FieldContainerType holds the string denoting the container_type field in the database.
	FieldContainerType = "container_type"
	// FieldThumbnailIndex holds the string denoting the thumbnail_index field in the database.
	FieldThumbnailIndex = "thumbnail_index"
	// FieldThumbnailX holds the string denoting the thumbnail_x field in the database.
	FieldThumbnailX = "thumbnail_x"
	// FieldThumbnailY holds the string denoting the thumbnail_y field in the database.
	FieldThumbnailY = "thumbnail_y"
	// FieldThumbnailWidth holds the string denoting the thumbnail_width field in the database.
	FieldThumbnailWidth = "thumbnail_width"
	// FieldThumbnailHeight holds the string denoting the thumbnail_height field in the database.
	FieldThumbnailHeight = "thumbnail_height"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// EdgeHistories holds the string denoting the histories edge name in mutations.
	EdgeHistories = "histories"
	// EdgeFavoriteOfUser holds the string denoting the favorite_of_user edge name in mutations.
	EdgeFavoriteOfUser = "favorite_of_user"
	// EdgeProgress holds the string denoting the progress edge name in mutations.
	EdgeProgress = "progress"
	// Table holds the table name of the meta in the database.
	Table = "meta"
	// TagsTable is the table that holds the tags relation/edge. The primary key declared below.
	TagsTable = "meta_tags"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
	// HistoriesTable is the table that holds the histories relation/edge.
	HistoriesTable = "histories"
	// HistoriesInverseTable is the table name for the History entity.
	// It exists in this package in order to avoid circular dependency with the "history" package.
	HistoriesInverseTable = "histories"
	// HistoriesColumn is the table column denoting the histories relation/edge.
	HistoriesColumn = "meta_histories"
	// FavoriteOfUserTable is the table that holds the favorite_of_user relation/edge. The primary key declared below.
	FavoriteOfUserTable = "user_favorite_items"
	// FavoriteOfUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	FavoriteOfUserInverseTable = "users"
	// ProgressTable is the table that holds the progress relation/edge.
	ProgressTable = "progresses"
	// ProgressInverseTable is the table name for the Progress entity.
	// It exists in this package in order to avoid circular dependency with the "progress" package.
	ProgressInverseTable = "progresses"
	// ProgressColumn is the table column denoting the progress relation/edge.
	ProgressColumn = "item_id"
)

// Columns holds all SQL columns for meta fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCreateTime,
	FieldFileIndices,
	FieldActive,
	FieldHidden,
	FieldContainerType,
	FieldThumbnailIndex,
	FieldThumbnailX,
	FieldThumbnailY,
	FieldThumbnailWidth,
	FieldThumbnailHeight,
}

var (
	// TagsPrimaryKey and TagsColumn2 are the table columns denoting the
	// primary key for the tags relation (M2M).
	TagsPrimaryKey = []string{"meta_id", "tag_id"}
	// FavoriteOfUserPrimaryKey and FavoriteOfUserColumn2 are the table columns denoting the
	// primary key for the favorite_of_user relation (M2M).
	FavoriteOfUserPrimaryKey = []string{"user_id", "meta_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for _, f := range [...]string{FieldFavorite, FieldRead} {
		if column == f {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultFavorite holds the default value on creation for the "favorite" field.
	DefaultFavorite bool
	// DefaultFileIndices holds the default value on creation for the "file_indices" field.
	DefaultFileIndices []int
	// DefaultRead holds the default value on creation for the "read" field.
	DefaultRead bool
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultHidden holds the default value on creation for the "hidden" field.
	DefaultHidden bool
	// DefaultThumbnailIndex holds the default value on creation for the "thumbnail_index" field.
	DefaultThumbnailIndex int
	// DefaultThumbnailX holds the default value on creation for the "thumbnail_x" field.
	DefaultThumbnailX int
	// DefaultThumbnailY holds the default value on creation for the "thumbnail_y" field.
	DefaultThumbnailY int
	// DefaultThumbnailWidth holds the default value on creation for the "thumbnail_width" field.
	DefaultThumbnailWidth int
	// DefaultThumbnailHeight holds the default value on creation for the "thumbnail_height" field.
	DefaultThumbnailHeight int
)

// ContainerType defines the type for the "container_type" enum field.
type ContainerType string

// ContainerTypeZip is the default value of the ContainerType enum.
const DefaultContainerType = ContainerTypeZip

// ContainerType values.
const (
	ContainerTypeZip       ContainerType = "zip"
	ContainerTypeDirectory ContainerType = "directory"
)

func (ct ContainerType) String() string {
	return string(ct)
}

// ContainerTypeValidator is a validator for the "container_type" field enum values. It is called by the builders before save.
func ContainerTypeValidator(ct ContainerType) error {
	switch ct {
	case ContainerTypeZip, ContainerTypeDirectory:
		return nil
	default:
		return fmt.Errorf("meta: invalid enum value for container_type field: %q", ct)
	}
}

// OrderOption defines the ordering options for the Meta queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByFavorite orders the results by the favorite field.
func ByFavorite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFavorite, opts...).ToFunc()
}

// ByRead orders the results by the read field.
func ByRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRead, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByHidden orders the results by the hidden field.
func ByHidden(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHidden, opts...).ToFunc()
}

// ByContainerType orders the results by the container_type field.
func ByContainerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContainerType, opts...).ToFunc()
}

// ByThumbnailIndex orders the results by the thumbnail_index field.
func ByThumbnailIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnailIndex, opts...).ToFunc()
}

// ByThumbnailX orders the results by the thumbnail_x field.
func ByThumbnailX(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnailX, opts...).ToFunc()
}

// ByThumbnailY orders the results by the thumbnail_y field.
func ByThumbnailY(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnailY, opts...).ToFunc()
}

// ByThumbnailWidth orders the results by the thumbnail_width field.
func ByThumbnailWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnailWidth, opts...).ToFunc()
}

// ByThumbnailHeight orders the results by the thumbnail_height field.
func ByThumbnailHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnailHeight, opts...).ToFunc()
}

// ByTagsCount orders the results by tags count.
func ByTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTagsStep(), opts...)
	}
}

// ByTags orders the results by tags terms.
func ByTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByHistoriesCount orders the results by histories count.
func ByHistoriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHistoriesStep(), opts...)
	}
}

// ByHistories orders the results by histories terms.
func ByHistories(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHistoriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFavoriteOfUserCount orders the results by favorite_of_user count.
func ByFavoriteOfUserCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFavoriteOfUserStep(), opts...)
	}
}

// ByFavoriteOfUser orders the results by favorite_of_user terms.
func ByFavoriteOfUser(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFavoriteOfUserStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProgressCount orders the results by progress count.
func ByProgressCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProgressStep(), opts...)
	}
}

// ByProgress orders the results by progress terms.
func ByProgress(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProgressStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
	)
}
func newHistoriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HistoriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HistoriesTable, HistoriesColumn),
	)
}
func newFavoriteOfUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FavoriteOfUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, FavoriteOfUserTable, FavoriteOfUserPrimaryKey...),
	)
}
func newProgressStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProgressInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProgressTable, ProgressColumn),
	)
}
