// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/mangaweb4/mangaweb4-backend/ent/history"
	"github.com/mangaweb4/mangaweb4-backend/ent/meta"
	"github.com/mangaweb4/mangaweb4-backend/ent/predicate"
	"github.com/mangaweb4/mangaweb4-backend/ent/progress"
	"github.com/mangaweb4/mangaweb4-backend/ent/tag"
	"github.com/mangaweb4/mangaweb4-backend/ent/user"
)

// MetaUpdate is the builder for updating Meta entities.
type MetaUpdate struct {
	config
	hooks    []Hook
	mutation *MetaMutation
}

// Where appends a list predicates to the MetaUpdate builder.
func (_u *MetaUpdate) Where(ps ...predicate.Meta) *MetaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MetaUpdate) SetName(v string) *MetaUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableName(v *string) *MetaUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *MetaUpdate) SetCreateTime(v time.Time) *MetaUpdate {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableCreateTime(v *time.Time) *MetaUpdate {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// SetFavorite sets the "favorite" field.
func (_u *MetaUpdate) SetFavorite(v bool) *MetaUpdate {
	_u.mutation.SetFavorite(v)
	return _u
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableFavorite(v *bool) *MetaUpdate {
	if v != nil {
		_u.SetFavorite(*v)
	}
	return _u
}

// SetFileIndices sets the "file_indices" field.
func (_u *MetaUpdate) SetFileIndices(v []int) *MetaUpdate {
	_u.mutation.SetFileIndices(v)
	return _u
}

// AppendFileIndices appends value to the "file_indices" field.
func (_u *MetaUpdate) AppendFileIndices(v []int) *MetaUpdate {
	_u.mutation.AppendFileIndices(v)
	return _u
}

// SetRead sets the "read" field.
func (_u *MetaUpdate) SetRead(v bool) *MetaUpdate {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableRead(v *bool) *MetaUpdate {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *MetaUpdate) SetActive(v bool) *MetaUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableActive(v *bool) *MetaUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetHidden sets the "hidden" field.
func (_u *MetaUpdate) SetHidden(v bool) *MetaUpdate {
	_u.mutation.SetHidden(v)
	return _u
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableHidden(v *bool) *MetaUpdate {
	if v != nil {
		_u.SetHidden(*v)
	}
	return _u
}

// SetContainerType sets the "container_type" field.
func (_u *MetaUpdate) SetContainerType(v meta.ContainerType) *MetaUpdate {
	_u.mutation.SetContainerType(v)
	return _u
}

// SetNillableContainerType sets the "container_type" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableContainerType(v *meta.ContainerType) *MetaUpdate {
	if v != nil {
		_u.SetContainerType(*v)
	}
	return _u
}

// SetThumbnailIndex sets the "thumbnail_index" field.
func (_u *MetaUpdate) SetThumbnailIndex(v int) *MetaUpdate {
	_u.mutation.ResetThumbnailIndex()
	_u.mutation.SetThumbnailIndex(v)
	return _u
}

// SetNillableThumbnailIndex sets the "thumbnail_index" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableThumbnailIndex(v *int) *MetaUpdate {
	if v != nil {
		_u.SetThumbnailIndex(*v)
	}
	return _u
}

// AddThumbnailIndex adds value to the "thumbnail_index" field.
func (_u *MetaUpdate) AddThumbnailIndex(v int) *MetaUpdate {
	_u.mutation.AddThumbnailIndex(v)
	return _u
}

// ClearThumbnailIndex clears the value of the "thumbnail_index" field.
func (_u *MetaUpdate) ClearThumbnailIndex() *MetaUpdate {
	_u.mutation.ClearThumbnailIndex()
	return _u
}

// SetThumbnailX sets the "thumbnail_x" field.
func (_u *MetaUpdate) SetThumbnailX(v int) *MetaUpdate {
	_u.mutation.ResetThumbnailX()
	_u.mutation.SetThumbnailX(v)
	return _u
}

// SetNillableThumbnailX sets the "thumbnail_x" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableThumbnailX(v *int) *MetaUpdate {
	if v != nil {
		_u.SetThumbnailX(*v)
	}
	return _u
}

// AddThumbnailX adds value to the "thumbnail_x" field.
func (_u *MetaUpdate) AddThumbnailX(v int) *MetaUpdate {
	_u.mutation.AddThumbnailX(v)
	return _u
}

// ClearThumbnailX clears the value of the "thumbnail_x" field.
func (_u *MetaUpdate) ClearThumbnailX() *MetaUpdate {
	_u.mutation.ClearThumbnailX()
	return _u
}

// SetThumbnailY sets the "thumbnail_y" field.
func (_u *MetaUpdate) SetThumbnailY(v int) *MetaUpdate {
	_u.mutation.ResetThumbnailY()
	_u.mutation.SetThumbnailY(v)
	return _u
}

// SetNillableThumbnailY sets the "thumbnail_y" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableThumbnailY(v *int) *MetaUpdate {
	if v != nil {
		_u.SetThumbnailY(*v)
	}
	return _u
}

// AddThumbnailY adds value to the "thumbnail_y" field.
func (_u *MetaUpdate) AddThumbnailY(v int) *MetaUpdate {
	_u.mutation.AddThumbnailY(v)
	return _u
}

// ClearThumbnailY clears the value of the "thumbnail_y" field.
func (_u *MetaUpdate) ClearThumbnailY() *MetaUpdate {
	_u.mutation.ClearThumbnailY()
	return _u
}

// SetThumbnailWidth sets the "thumbnail_width" field.
func (_u *MetaUpdate) SetThumbnailWidth(v int) *MetaUpdate {
	_u.mutation.ResetThumbnailWidth()
	_u.mutation.SetThumbnailWidth(v)
	return _u
}

// SetNillableThumbnailWidth sets the "thumbnail_width" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableThumbnailWidth(v *int) *MetaUpdate {
	if v != nil {
		_u.SetThumbnailWidth(*v)
	}
	return _u
}

// AddThumbnailWidth adds value to the "thumbnail_width" field.
func (_u *MetaUpdate) AddThumbnailWidth(v int) *MetaUpdate {
	_u.mutation.AddThumbnailWidth(v)
	return _u
}

// ClearThumbnailWidth clears the value of the "thumbnail_width" field.
func (_u *MetaUpdate) ClearThumbnailWidth() *MetaUpdate {
	_u.mutation.ClearThumbnailWidth()
	return _u
}

// SetThumbnailHeight sets the "thumbnail_height" field.
func (_u *MetaUpdate) SetThumbnailHeight(v int) *MetaUpdate {
	_u.mutation.ResetThumbnailHeight()
	_u.mutation.SetThumbnailHeight(v)
	return _u
}

// SetNillableThumbnailHeight sets the "thumbnail_height" field if the given value is not nil.
func (_u *MetaUpdate) SetNillableThumbnailHeight(v *int) *MetaUpdate {
	if v != nil {
		_u.SetThumbnailHeight(*v)
	}
	return _u
}

// AddThumbnailHeight adds value to the "thumbnail_height" field.
func (_u *MetaUpdate) AddThumbnailHeight(v int) *MetaUpdate {
	_u.mutation.AddThumbnailHeight(v)
	return _u
}

// ClearThumbnailHeight clears the value of the "thumbnail_height" field.
func (_u *MetaUpdate) ClearThumbnailHeight() *MetaUpdate {
	_u.mutation.ClearThumbnailHeight()
	return _u
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *MetaUpdate) AddTagIDs(ids ...int) *MetaUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *MetaUpdate) AddTags(v ...*Tag) *MetaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddHistoryIDs adds the "histories" edge to the History entity by IDs.
func (_u *MetaUpdate) AddHistoryIDs(ids ...int) *MetaUpdate {
	_u.mutation.AddHistoryIDs(ids...)
	return _u
}

// AddHistories adds the "histories" edges to the History entity.
func (_u *MetaUpdate) AddHistories(v ...*History) *MetaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHistoryIDs(ids...)
}

// AddFavoriteOfUserIDs adds the "favorite_of_user" edge to the User entity by IDs.
func (_u *MetaUpdate) AddFavoriteOfUserIDs(ids ...int) *MetaUpdate {
	_u.mutation.AddFavoriteOfUserIDs(ids...)
	return _u
}

// AddFavoriteOfUser adds the "favorite_of_user" edges to the User entity.
func (_u *MetaUpdate) AddFavoriteOfUser(v ...*User) *MetaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFavoriteOfUserIDs(ids...)
}

// AddProgresIDs adds the "progress" edge to the Progress entity by IDs.
func (_u *MetaUpdate) AddProgresIDs(ids ...int) *MetaUpdate {
	_u.mutation.AddProgresIDs(ids...)
	return _u
}

// AddProgress adds the "progress" edges to the Progress entity.
func (_u *MetaUpdate) AddProgress(v ...*Progress) *MetaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProgresIDs(ids...)
}

// Mutation returns the MetaMutation object of the builder.
func (_u *MetaUpdate) Mutation() *MetaMutation {
	return _u.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *MetaUpdate) ClearTags() *MetaUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *MetaUpdate) RemoveTagIDs(ids ...int) *MetaUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *MetaUpdate) RemoveTags(v ...*Tag) *MetaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearHistories clears all "histories" edges to the History entity.
func (_u *MetaUpdate) ClearHistories() *MetaUpdate {
	_u.mutation.ClearHistories()
	return _u
}

// RemoveHistoryIDs removes the "histories" edge to History entities by IDs.
func (_u *MetaUpdate) RemoveHistoryIDs(ids ...int) *MetaUpdate {
	_u.mutation.RemoveHistoryIDs(ids...)
	return _u
}

// RemoveHistories removes "histories" edges to History entities.
func (_u *MetaUpdate) RemoveHistories(v ...*History) *MetaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHistoryIDs(ids...)
}

// ClearFavoriteOfUser clears all "favorite_of_user" edges to the User entity.
func (_u *MetaUpdate) ClearFavoriteOfUser() *MetaUpdate {
	_u.mutation.ClearFavoriteOfUser()
	return _u
}

// RemoveFavoriteOfUserIDs removes the "favorite_of_user" edge to User entities by IDs.
func (_u *MetaUpdate) RemoveFavoriteOfUserIDs(ids ...int) *MetaUpdate {
	_u.mutation.RemoveFavoriteOfUserIDs(ids...)
	return _u
}

// RemoveFavoriteOfUser removes "favorite_of_user" edges to User entities.
func (_u *MetaUpdate) RemoveFavoriteOfUser(v ...*User) *MetaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFavoriteOfUserIDs(ids...)
}

// ClearProgress clears all "progress" edges to the Progress entity.
func (_u *MetaUpdate) ClearProgress() *MetaUpdate {
	_u.mutation.ClearProgress()
	return _u
}

// RemoveProgresIDs removes the "progress" edge to Progress entities by IDs.
func (_u *MetaUpdate) RemoveProgresIDs(ids ...int) *MetaUpdate {
	_u.mutation.RemoveProgresIDs(ids...)
	return _u
}

// RemoveProgress removes "progress" edges to Progress entities.
func (_u *MetaUpdate) RemoveProgress(v ...*Progress) *MetaUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProgresIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MetaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MetaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MetaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MetaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MetaUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := meta.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Meta.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContainerType(); ok {
		if err := meta.ContainerTypeValidator(v); err != nil {
			return &ValidationError{Name: "container_type", err: fmt.Errorf(`ent: validator failed for field "Meta.container_type": %w`, err)}
		}
	}
	return nil
}

func (_u *MetaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(meta.Table, meta.Columns, sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(meta.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(meta.FieldCreateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Favorite(); ok {
		_spec.SetField(meta.FieldFavorite, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FileIndices(); ok {
		_spec.SetField(meta.FieldFileIndices, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFileIndices(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, meta.FieldFileIndices, value)
		})
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(meta.FieldRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(meta.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Hidden(); ok {
		_spec.SetField(meta.FieldHidden, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ContainerType(); ok {
		_spec.SetField(meta.FieldContainerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ThumbnailIndex(); ok {
		_spec.SetField(meta.FieldThumbnailIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThumbnailIndex(); ok {
		_spec.AddField(meta.FieldThumbnailIndex, field.TypeInt, value)
	}
	if _u.mutation.ThumbnailIndexCleared() {
		_spec.ClearField(meta.FieldThumbnailIndex, field.TypeInt)
	}
	if value, ok := _u.mutation.ThumbnailX(); ok {
		_spec.SetField(meta.FieldThumbnailX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThumbnailX(); ok {
		_spec.AddField(meta.FieldThumbnailX, field.TypeInt, value)
	}
	if _u.mutation.ThumbnailXCleared() {
		_spec.ClearField(meta.FieldThumbnailX, field.TypeInt)
	}
	if value, ok := _u.mutation.ThumbnailY(); ok {
		_spec.SetField(meta.FieldThumbnailY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThumbnailY(); ok {
		_spec.AddField(meta.FieldThumbnailY, field.TypeInt, value)
	}
	if _u.mutation.ThumbnailYCleared() {
		_spec.ClearField(meta.FieldThumbnailY, field.TypeInt)
	}
	if value, ok := _u.mutation.ThumbnailWidth(); ok {
		_spec.SetField(meta.FieldThumbnailWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThumbnailWidth(); ok {
		_spec.AddField(meta.FieldThumbnailWidth, field.TypeInt, value)
	}
	if _u.mutation.ThumbnailWidthCleared() {
		_spec.ClearField(meta.FieldThumbnailWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.ThumbnailHeight(); ok {
		_spec.SetField(meta.FieldThumbnailHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThumbnailHeight(); ok {
		_spec.AddField(meta.FieldThumbnailHeight, field.TypeInt, value)
	}
	if _u.mutation.ThumbnailHeightCleared() {
		_spec.ClearField(meta.FieldThumbnailHeight, field.TypeInt)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHistoriesIDs(); len(nodes) > 0 && !_u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFavoriteOfUserIDs(); len(nodes) > 0 && !_u.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FavoriteOfUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProgressIDs(); len(nodes) > 0 && !_u.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProgressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{meta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MetaUpdateOne is the builder for updating a single Meta entity.
type MetaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MetaMutation
}

// SetName sets the "name" field.
func (_u *MetaUpdateOne) SetName(v string) *MetaUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableName(v *string) *MetaUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCreateTime sets the "create_time" field.
func (_u *MetaUpdateOne) SetCreateTime(v time.Time) *MetaUpdateOne {
	_u.mutation.SetCreateTime(v)
	return _u
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableCreateTime(v *time.Time) *MetaUpdateOne {
	if v != nil {
		_u.SetCreateTime(*v)
	}
	return _u
}

// SetFavorite sets the "favorite" field.
func (_u *MetaUpdateOne) SetFavorite(v bool) *MetaUpdateOne {
	_u.mutation.SetFavorite(v)
	return _u
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableFavorite(v *bool) *MetaUpdateOne {
	if v != nil {
		_u.SetFavorite(*v)
	}
	return _u
}

// SetFileIndices sets the "file_indices" field.
func (_u *MetaUpdateOne) SetFileIndices(v []int) *MetaUpdateOne {
	_u.mutation.SetFileIndices(v)
	return _u
}

// AppendFileIndices appends value to the "file_indices" field.
func (_u *MetaUpdateOne) AppendFileIndices(v []int) *MetaUpdateOne {
	_u.mutation.AppendFileIndices(v)
	return _u
}

// SetRead sets the "read" field.
func (_u *MetaUpdateOne) SetRead(v bool) *MetaUpdateOne {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableRead(v *bool) *MetaUpdateOne {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *MetaUpdateOne) SetActive(v bool) *MetaUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableActive(v *bool) *MetaUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetHidden sets the "hidden" field.
func (_u *MetaUpdateOne) SetHidden(v bool) *MetaUpdateOne {
	_u.mutation.SetHidden(v)
	return _u
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableHidden(v *bool) *MetaUpdateOne {
	if v != nil {
		_u.SetHidden(*v)
	}
	return _u
}

// SetContainerType sets the "container_type" field.
func (_u *MetaUpdateOne) SetContainerType(v meta.ContainerType) *MetaUpdateOne {
	_u.mutation.SetContainerType(v)
	return _u
}

// SetNillableContainerType sets the "container_type" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableContainerType(v *meta.ContainerType) *MetaUpdateOne {
	if v != nil {
		_u.SetContainerType(*v)
	}
	return _u
}

// SetThumbnailIndex sets the "thumbnail_index" field.
func (_u *MetaUpdateOne) SetThumbnailIndex(v int) *MetaUpdateOne {
	_u.mutation.ResetThumbnailIndex()
	_u.mutation.SetThumbnailIndex(v)
	return _u
}

// SetNillableThumbnailIndex sets the "thumbnail_index" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableThumbnailIndex(v *int) *MetaUpdateOne {
	if v != nil {
		_u.SetThumbnailIndex(*v)
	}
	return _u
}

// AddThumbnailIndex adds value to the "thumbnail_index" field.
func (_u *MetaUpdateOne) AddThumbnailIndex(v int) *MetaUpdateOne {
	_u.mutation.AddThumbnailIndex(v)
	return _u
}

// ClearThumbnailIndex clears the value of the "thumbnail_index" field.
func (_u *MetaUpdateOne) ClearThumbnailIndex() *MetaUpdateOne {
	_u.mutation.ClearThumbnailIndex()
	return _u
}

// SetThumbnailX sets the "thumbnail_x" field.
func (_u *MetaUpdateOne) SetThumbnailX(v int) *MetaUpdateOne {
	_u.mutation.ResetThumbnailX()
	_u.mutation.SetThumbnailX(v)
	return _u
}

// SetNillableThumbnailX sets the "thumbnail_x" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableThumbnailX(v *int) *MetaUpdateOne {
	if v != nil {
		_u.SetThumbnailX(*v)
	}
	return _u
}

// AddThumbnailX adds value to the "thumbnail_x" field.
func (_u *MetaUpdateOne) AddThumbnailX(v int) *MetaUpdateOne {
	_u.mutation.AddThumbnailX(v)
	return _u
}

// ClearThumbnailX clears the value of the "thumbnail_x" field.
func (_u *MetaUpdateOne) ClearThumbnailX() *MetaUpdateOne {
	_u.mutation.ClearThumbnailX()
	return _u
}

// SetThumbnailY sets the "thumbnail_y" field.
func (_u *MetaUpdateOne) SetThumbnailY(v int) *MetaUpdateOne {
	_u.mutation.ResetThumbnailY()
	_u.mutation.SetThumbnailY(v)
	return _u
}

// SetNillableThumbnailY sets the "thumbnail_y" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableThumbnailY(v *int) *MetaUpdateOne {
	if v != nil {
		_u.SetThumbnailY(*v)
	}
	return _u
}

// AddThumbnailY adds value to the "thumbnail_y" field.
func (_u *MetaUpdateOne) AddThumbnailY(v int) *MetaUpdateOne {
	_u.mutation.AddThumbnailY(v)
	return _u
}

// ClearThumbnailY clears the value of the "thumbnail_y" field.
func (_u *MetaUpdateOne) ClearThumbnailY() *MetaUpdateOne {
	_u.mutation.ClearThumbnailY()
	return _u
}

// SetThumbnailWidth sets the "thumbnail_width" field.
func (_u *MetaUpdateOne) SetThumbnailWidth(v int) *MetaUpdateOne {
	_u.mutation.ResetThumbnailWidth()
	_u.mutation.SetThumbnailWidth(v)
	return _u
}

// SetNillableThumbnailWidth sets the "thumbnail_width" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableThumbnailWidth(v *int) *MetaUpdateOne {
	if v != nil {
		_u.SetThumbnailWidth(*v)
	}
	return _u
}

// AddThumbnailWidth adds value to the "thumbnail_width" field.
func (_u *MetaUpdateOne) AddThumbnailWidth(v int) *MetaUpdateOne {
	_u.mutation.AddThumbnailWidth(v)
	return _u
}

// ClearThumbnailWidth clears the value of the "thumbnail_width" field.
func (_u *MetaUpdateOne) ClearThumbnailWidth() *MetaUpdateOne {
	_u.mutation.ClearThumbnailWidth()
	return _u
}

// SetThumbnailHeight sets the "thumbnail_height" field.
func (_u *MetaUpdateOne) SetThumbnailHeight(v int) *MetaUpdateOne {
	_u.mutation.ResetThumbnailHeight()
	_u.mutation.SetThumbnailHeight(v)
	return _u
}

// SetNillableThumbnailHeight sets the "thumbnail_height" field if the given value is not nil.
func (_u *MetaUpdateOne) SetNillableThumbnailHeight(v *int) *MetaUpdateOne {
	if v != nil {
		_u.SetThumbnailHeight(*v)
	}
	return _u
}

// AddThumbnailHeight adds value to the "thumbnail_height" field.
func (_u *MetaUpdateOne) AddThumbnailHeight(v int) *MetaUpdateOne {
	_u.mutation.AddThumbnailHeight(v)
	return _u
}

// ClearThumbnailHeight clears the value of the "thumbnail_height" field.
func (_u *MetaUpdateOne) ClearThumbnailHeight() *MetaUpdateOne {
	_u.mutation.ClearThumbnailHeight()
	return _u
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *MetaUpdateOne) AddTagIDs(ids ...int) *MetaUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *MetaUpdateOne) AddTags(v ...*Tag) *MetaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// AddHistoryIDs adds the "histories" edge to the History entity by IDs.
func (_u *MetaUpdateOne) AddHistoryIDs(ids ...int) *MetaUpdateOne {
	_u.mutation.AddHistoryIDs(ids...)
	return _u
}

// AddHistories adds the "histories" edges to the History entity.
func (_u *MetaUpdateOne) AddHistories(v ...*History) *MetaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHistoryIDs(ids...)
}

// AddFavoriteOfUserIDs adds the "favorite_of_user" edge to the User entity by IDs.
func (_u *MetaUpdateOne) AddFavoriteOfUserIDs(ids ...int) *MetaUpdateOne {
	_u.mutation.AddFavoriteOfUserIDs(ids...)
	return _u
}

// AddFavoriteOfUser adds the "favorite_of_user" edges to the User entity.
func (_u *MetaUpdateOne) AddFavoriteOfUser(v ...*User) *MetaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFavoriteOfUserIDs(ids...)
}

// AddProgresIDs adds the "progress" edge to the Progress entity by IDs.
func (_u *MetaUpdateOne) AddProgresIDs(ids ...int) *MetaUpdateOne {
	_u.mutation.AddProgresIDs(ids...)
	return _u
}

// AddProgress adds the "progress" edges to the Progress entity.
func (_u *MetaUpdateOne) AddProgress(v ...*Progress) *MetaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProgresIDs(ids...)
}

// Mutation returns the MetaMutation object of the builder.
func (_u *MetaUpdateOne) Mutation() *MetaMutation {
	return _u.mutation
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *MetaUpdateOne) ClearTags() *MetaUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *MetaUpdateOne) RemoveTagIDs(ids ...int) *MetaUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *MetaUpdateOne) RemoveTags(v ...*Tag) *MetaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// ClearHistories clears all "histories" edges to the History entity.
func (_u *MetaUpdateOne) ClearHistories() *MetaUpdateOne {
	_u.mutation.ClearHistories()
	return _u
}

// RemoveHistoryIDs removes the "histories" edge to History entities by IDs.
func (_u *MetaUpdateOne) RemoveHistoryIDs(ids ...int) *MetaUpdateOne {
	_u.mutation.RemoveHistoryIDs(ids...)
	return _u
}

// RemoveHistories removes "histories" edges to History entities.
func (_u *MetaUpdateOne) RemoveHistories(v ...*History) *MetaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHistoryIDs(ids...)
}

// ClearFavoriteOfUser clears all "favorite_of_user" edges to the User entity.
func (_u *MetaUpdateOne) ClearFavoriteOfUser() *MetaUpdateOne {
	_u.mutation.ClearFavoriteOfUser()
	return _u
}

// RemoveFavoriteOfUserIDs removes the "favorite_of_user" edge to User entities by IDs.
func (_u *MetaUpdateOne) RemoveFavoriteOfUserIDs(ids ...int) *MetaUpdateOne {
	_u.mutation.RemoveFavoriteOfUserIDs(ids...)
	return _u
}

// RemoveFavoriteOfUser removes "favorite_of_user" edges to User entities.
func (_u *MetaUpdateOne) RemoveFavoriteOfUser(v ...*User) *MetaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFavoriteOfUserIDs(ids...)
}

// ClearProgress clears all "progress" edges to the Progress entity.
func (_u *MetaUpdateOne) ClearProgress() *MetaUpdateOne {
	_u.mutation.ClearProgress()
	return _u
}

// RemoveProgresIDs removes the "progress" edge to Progress entities by IDs.
func (_u *MetaUpdateOne) RemoveProgresIDs(ids ...int) *MetaUpdateOne {
	_u.mutation.RemoveProgresIDs(ids...)
	return _u
}

// RemoveProgress removes "progress" edges to Progress entities.
func (_u *MetaUpdateOne) RemoveProgress(v ...*Progress) *MetaUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProgresIDs(ids...)
}

// Where appends a list predicates to the MetaUpdate builder.
func (_u *MetaUpdateOne) Where(ps ...predicate.Meta) *MetaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MetaUpdateOne) Select(field string, fields ...string) *MetaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Meta entity.
func (_u *MetaUpdateOne) Save(ctx context.Context) (*Meta, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MetaUpdateOne) SaveX(ctx context.Context) *Meta {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MetaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MetaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MetaUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := meta.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Meta.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContainerType(); ok {
		if err := meta.ContainerTypeValidator(v); err != nil {
			return &ValidationError{Name: "container_type", err: fmt.Errorf(`ent: validator failed for field "Meta.container_type": %w`, err)}
		}
	}
	return nil
}

func (_u *MetaUpdateOne) sqlSave(ctx context.Context) (_node *Meta, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(meta.Table, meta.Columns, sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Meta.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meta.FieldID)
		for _, f := range fields {
			if !meta.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != meta.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(meta.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreateTime(); ok {
		_spec.SetField(meta.FieldCreateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Favorite(); ok {
		_spec.SetField(meta.FieldFavorite, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FileIndices(); ok {
		_spec.SetField(meta.FieldFileIndices, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFileIndices(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, meta.FieldFileIndices, value)
		})
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(meta.FieldRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(meta.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Hidden(); ok {
		_spec.SetField(meta.FieldHidden, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ContainerType(); ok {
		_spec.SetField(meta.FieldContainerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ThumbnailIndex(); ok {
		_spec.SetField(meta.FieldThumbnailIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThumbnailIndex(); ok {
		_spec.AddField(meta.FieldThumbnailIndex, field.TypeInt, value)
	}
	if _u.mutation.ThumbnailIndexCleared() {
		_spec.ClearField(meta.FieldThumbnailIndex, field.TypeInt)
	}
	if value, ok := _u.mutation.ThumbnailX(); ok {
		_spec.SetField(meta.FieldThumbnailX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThumbnailX(); ok {
		_spec.AddField(meta.FieldThumbnailX, field.TypeInt, value)
	}
	if _u.mutation.ThumbnailXCleared() {
		_spec.ClearField(meta.FieldThumbnailX, field.TypeInt)
	}
	if value, ok := _u.mutation.ThumbnailY(); ok {
		_spec.SetField(meta.FieldThumbnailY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThumbnailY(); ok {
		_spec.AddField(meta.FieldThumbnailY, field.TypeInt, value)
	}
	if _u.mutation.ThumbnailYCleared() {
		_spec.ClearField(meta.FieldThumbnailY, field.TypeInt)
	}
	if value, ok := _u.mutation.ThumbnailWidth(); ok {
		_spec.SetField(meta.FieldThumbnailWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThumbnailWidth(); ok {
		_spec.AddField(meta.FieldThumbnailWidth, field.TypeInt, value)
	}
	if _u.mutation.ThumbnailWidthCleared() {
		_spec.ClearField(meta.FieldThumbnailWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.ThumbnailHeight(); ok {
		_spec.SetField(meta.FieldThumbnailHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedThumbnailHeight(); ok {
		_spec.AddField(meta.FieldThumbnailHeight, field.TypeInt, value)
	}
	if _u.mutation.ThumbnailHeightCleared() {
		_spec.ClearField(meta.FieldThumbnailHeight, field.TypeInt)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   meta.TagsTable,
			Columns: meta.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHistoriesIDs(); len(nodes) > 0 && !_u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.HistoriesTable,
			Columns: []string{meta.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFavoriteOfUserIDs(); len(nodes) > 0 && !_u.mutation.FavoriteOfUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FavoriteOfUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   meta.FavoriteOfUserTable,
			Columns: meta.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProgressIDs(); len(nodes) > 0 && !_u.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProgressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   meta.ProgressTable,
			Columns: []string{meta.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Meta{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{meta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
