// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mangaweb4/mangaweb4-backend/ent/meta"
	"github.com/mangaweb4/mangaweb4-backend/ent/progress"
	"github.com/mangaweb4/mangaweb4-backend/ent/user"
)

// Progress is the model entity for the Progress schema.
type Progress struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Page holds the value of the "page" field.
	Page int `json:"page,omitempty"`
	// Max holds the value of the "max" field.
	Max int `json:"max,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID int `json:"item_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProgressQuery when eager-loading is set.
	Edges        ProgressEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProgressEdges holds the relations/edges for other nodes in the graph.
type ProgressEdges struct {
	// Item holds the value of the item edge.
	Item *Meta `json:"item,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ItemOrErr returns the Item value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProgressEdges) ItemOrErr() (*Meta, error) {
	if e.Item != nil {
		return e.Item, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: meta.Label}
	}
	return nil, &NotLoadedError{edge: "item"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProgressEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Progress) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case progress.FieldID, progress.FieldPage, progress.FieldMax, progress.FieldItemID, progress.FieldUserID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Progress fields.
func (_m *Progress) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case progress.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case progress.FieldPage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field page", values[i])
			} else if value.Valid {
				_m.Page = int(value.Int64)
			}
		case progress.FieldMax:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max", values[i])
			} else if value.Valid {
				_m.Max = int(value.Int64)
			}
		case progress.FieldItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				_m.ItemID = int(value.Int64)
			}
		case progress.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Progress.
// This includes values selected through modifiers, order, etc.
func (_m *Progress) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItem queries the "item" edge of the Progress entity.
func (_m *Progress) QueryItem() *MetaQuery {
	return NewProgressClient(_m.config).QueryItem(_m)
}

// QueryUser queries the "user" edge of the Progress entity.
func (_m *Progress) QueryUser() *UserQuery {
	return NewProgressClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Progress.
// Note that you need to call Progress.Unwrap() before calling this method if this Progress
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Progress) Update() *ProgressUpdateOne {
	return NewProgressClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Progress entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Progress) Unwrap() *Progress {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Progress is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Progress) String() string {
	var builder strings.Builder
	builder.WriteString("Progress(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("page=")
	builder.WriteString(fmt.Sprintf("%v", _m.Page))
	builder.WriteString(", ")
	builder.WriteString("max=")
	builder.WriteString(fmt.Sprintf("%v", _m.Max))
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ItemID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// Progresses is a parsable slice of Progress.
type Progresses []*Progress
