// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mangaweb4/mangaweb4-backend/ent/history"
	"github.com/mangaweb4/mangaweb4-backend/ent/meta"
	"github.com/mangaweb4/mangaweb4-backend/ent/progress"
	"github.com/mangaweb4/mangaweb4-backend/ent/schema"
	"github.com/mangaweb4/mangaweb4-backend/ent/tag"
	"github.com/mangaweb4/mangaweb4-backend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	historyFields := schema.History{}.Fields()
	_ = historyFields
	// historyDescCreateTime is the schema descriptor for create_time field.
	historyDescCreateTime := historyFields[0].Descriptor()
	// history.DefaultCreateTime holds the default value on creation for the create_time field.
	history.DefaultCreateTime = historyDescCreateTime.Default.(func() time.Time)
	metaFields := schema.Meta{}.Fields()
	_ = metaFields
	// metaDescName is the schema descriptor for name field.
	metaDescName := metaFields[0].Descriptor()
	// meta.NameValidator is a validator for the "name" field. It is called by the builders before save.
	meta.NameValidator = metaDescName.Validators[0].(func(string) error)
	// metaDescCreateTime is the schema descriptor for create_time field.
	metaDescCreateTime := metaFields[1].Descriptor()
	// meta.DefaultCreateTime holds the default value on creation for the create_time field.
	meta.DefaultCreateTime = metaDescCreateTime.Default.(func() time.Time)
	// metaDescFavorite is the schema descriptor for favorite field.
	metaDescFavorite := metaFields[2].Descriptor()
	// meta.DefaultFavorite holds the default value on creation for the favorite field.
	meta.DefaultFavorite = metaDescFavorite.Default.(bool)
	// metaDescFileIndices is the schema descriptor for file_indices field.
	metaDescFileIndices := metaFields[3].Descriptor()
	// meta.DefaultFileIndices holds the default value on creation for the file_indices field.
	meta.DefaultFileIndices = metaDescFileIndices.Default.([]int)
	// metaDescRead is the schema descriptor for read field.
	metaDescRead := metaFields[4].Descriptor()
	// meta.DefaultRead holds the default value on creation for the read field.
	meta.DefaultRead = metaDescRead.Default.(bool)
	// metaDescActive is the schema descriptor for active field.
	metaDescActive := metaFields[5].Descriptor()
	// meta.DefaultActive holds the default value on creation for the active field.
	meta.DefaultActive = metaDescActive.Default.(bool)
	// metaDescHidden is the schema descriptor for hidden field.
	metaDescHidden := metaFields[6].Descriptor()
	// meta.DefaultHidden holds the default value on creation for the hidden field.
	meta.DefaultHidden = metaDescHidden.Default.(bool)
	// metaDescThumbnailIndex is the schema descriptor for thumbnail_index field.
	metaDescThumbnailIndex := metaFields[8].Descriptor()
	// meta.DefaultThumbnailIndex holds the default value on creation for the thumbnail_index field.
	meta.DefaultThumbnailIndex = metaDescThumbnailIndex.Default.(int)
	// metaDescThumbnailX is the schema descriptor for thumbnail_x field.
	metaDescThumbnailX := metaFields[9].Descriptor()
	// meta.DefaultThumbnailX holds the default value on creation for the thumbnail_x field.
	meta.DefaultThumbnailX = metaDescThumbnailX.Default.(int)
	// metaDescThumbnailY is the schema descriptor for thumbnail_y field.
	metaDescThumbnailY := metaFields[10].Descriptor()
	// meta.DefaultThumbnailY holds the default value on creation for the thumbnail_y field.
	meta.DefaultThumbnailY = metaDescThumbnailY.Default.(int)
	// metaDescThumbnailWidth is the schema descriptor for thumbnail_width field.
	metaDescThumbnailWidth := metaFields[11].Descriptor()
	// meta.DefaultThumbnailWidth holds the default value on creation for the thumbnail_width field.
	meta.DefaultThumbnailWidth = metaDescThumbnailWidth.Default.(int)
	// metaDescThumbnailHeight is the schema descriptor for thumbnail_height field.
	metaDescThumbnailHeight := metaFields[12].Descriptor()
	// meta.DefaultThumbnailHeight holds the default value on creation for the thumbnail_height field.
	meta.DefaultThumbnailHeight = metaDescThumbnailHeight.Default.(int)
	progressFields := schema.Progress{}.Fields()
	_ = progressFields
	// progressDescPage is the schema descriptor for page field.
	progressDescPage := progressFields[0].Descriptor()
	// progress.DefaultPage holds the default value on creation for the page field.
	progress.DefaultPage = progressDescPage.Default.(int)
	// progressDescMax is the schema descriptor for max field.
	progressDescMax := progressFields[1].Descriptor()
	// progress.DefaultMax holds the default value on creation for the max field.
	progress.DefaultMax = progressDescMax.Default.(int)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[0].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	// tagDescFavorite is the schema descriptor for favorite field.
	tagDescFavorite := tagFields[1].Descriptor()
	// tag.DefaultFavorite holds the default value on creation for the favorite field.
	tag.DefaultFavorite = tagDescFavorite.Default.(bool)
	// tagDescHidden is the schema descriptor for hidden field.
	tagDescHidden := tagFields[2].Descriptor()
	// tag.DefaultHidden holds the default value on creation for the hidden field.
	tag.DefaultHidden = tagDescHidden.Default.(bool)
	// tagDescLastUpdate is the schema descriptor for last_update field.
	tagDescLastUpdate := tagFields[3].Descriptor()
	// tag.DefaultLastUpdate holds the default value on creation for the last_update field.
	tag.DefaultLastUpdate = tagDescLastUpdate.Default.(time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[1].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
}
