// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mangaweb4/mangaweb4-backend/ent/tag"
)

// Tag is the model entity for the Tag schema.
type Tag struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Favorite holds the value of the "favorite" field.
	//
	// Deprecated: use 'favorite_of_user' edge instead.
	Favorite bool `json:"favorite,omitempty"`
	// Hidden holds the value of the "hidden" field.
	Hidden bool `json:"hidden,omitempty"`
	// LastUpdate holds the value of the "last_update" field.
	LastUpdate time.Time `json:"last_update,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TagQuery when eager-loading is set.
	Edges        TagEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TagEdges holds the relations/edges for other nodes in the graph.
type TagEdges struct {
	// Meta holds the value of the meta edge.
	Meta []*Meta `json:"meta,omitempty"`
	// FavoriteOfUser holds the value of the favorite_of_user edge.
	FavoriteOfUser []*User `json:"favorite_of_user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MetaOrErr returns the Meta value or an error if the edge
// was not loaded in eager-loading.
func (e TagEdges) MetaOrErr() ([]*Meta, error) {
	if e.loadedTypes[0] {
		return e.Meta, nil
	}
	return nil, &NotLoadedError{edge: "meta"}
}

// FavoriteOfUserOrErr returns the FavoriteOfUser value or an error if the edge
// was not loaded in eager-loading.
func (e TagEdges) FavoriteOfUserOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.FavoriteOfUser, nil
	}
	return nil, &NotLoadedError{edge: "favorite_of_user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tag.FieldFavorite, tag.FieldHidden:
			values[i] = new(sql.NullBool)
		case tag.FieldID:
			values[i] = new(sql.NullInt64)
		case tag.FieldName:
			values[i] = new(sql.NullString)
		case tag.FieldLastUpdate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tag fields.
func (_m *Tag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case tag.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case tag.FieldFavorite:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field favorite", values[i])
			} else if value.Valid {
				_m.Favorite = value.Bool
			}
		case tag.FieldHidden:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field hidden", values[i])
			} else if value.Valid {
				_m.Hidden = value.Bool
			}
		case tag.FieldLastUpdate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_update", values[i])
			} else if value.Valid {
				_m.LastUpdate = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tag.
// This includes values selected through modifiers, order, etc.
func (_m *Tag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMeta queries the "meta" edge of the Tag entity.
func (_m *Tag) QueryMeta() *MetaQuery {
	return NewTagClient(_m.config).QueryMeta(_m)
}

// QueryFavoriteOfUser queries the "favorite_of_user" edge of the Tag entity.
func (_m *Tag) QueryFavoriteOfUser() *UserQuery {
	return NewTagClient(_m.config).QueryFavoriteOfUser(_m)
}

// Update returns a builder for updating this Tag.
// Note that you need to call Tag.Unwrap() before calling this method if this Tag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tag) Update() *TagUpdateOne {
	return NewTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tag) Unwrap() *Tag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tag) String() string {
	var builder strings.Builder
	builder.WriteString("Tag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("favorite=")
	builder.WriteString(fmt.Sprintf("%v", _m.Favorite))
	builder.WriteString(", ")
	builder.WriteString("hidden=")
	builder.WriteString(fmt.Sprintf("%v", _m.Hidden))
	builder.WriteString(", ")
	builder.WriteString("last_update=")
	builder.WriteString(_m.LastUpdate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tags is a parsable slice of Tag.
type Tags []*Tag
