// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mangaweb4/mangaweb4-backend/ent/meta"
	"github.com/mangaweb4/mangaweb4-backend/ent/tag"
	"github.com/mangaweb4/mangaweb4-backend/ent/user"
)

// TagCreate is the builder for creating a Tag entity.
type TagCreate struct {
	config
	mutation *TagMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *TagCreate) SetName(v string) *TagCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFavorite sets the "favorite" field.
func (_c *TagCreate) SetFavorite(v bool) *TagCreate {
	_c.mutation.SetFavorite(v)
	return _c
}

// SetNillableFavorite sets the "favorite" field if the given value is not nil.
func (_c *TagCreate) SetNillableFavorite(v *bool) *TagCreate {
	if v != nil {
		_c.SetFavorite(*v)
	}
	return _c
}

// SetHidden sets the "hidden" field.
func (_c *TagCreate) SetHidden(v bool) *TagCreate {
	_c.mutation.SetHidden(v)
	return _c
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (_c *TagCreate) SetNillableHidden(v *bool) *TagCreate {
	if v != nil {
		_c.SetHidden(*v)
	}
	return _c
}

// SetLastUpdate sets the "last_update" field.
func (_c *TagCreate) SetLastUpdate(v time.Time) *TagCreate {
	_c.mutation.SetLastUpdate(v)
	return _c
}

// SetNillableLastUpdate sets the "last_update" field if the given value is not nil.
func (_c *TagCreate) SetNillableLastUpdate(v *time.Time) *TagCreate {
	if v != nil {
		_c.SetLastUpdate(*v)
	}
	return _c
}

// AddMetumIDs adds the "meta" edge to the Meta entity by IDs.
func (_c *TagCreate) AddMetumIDs(ids ...int) *TagCreate {
	_c.mutation.AddMetumIDs(ids...)
	return _c
}

// AddMeta adds the "meta" edges to the Meta entity.
func (_c *TagCreate) AddMeta(v ...*Meta) *TagCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMetumIDs(ids...)
}

// AddFavoriteOfUserIDs adds the "favorite_of_user" edge to the User entity by IDs.
func (_c *TagCreate) AddFavoriteOfUserIDs(ids ...int) *TagCreate {
	_c.mutation.AddFavoriteOfUserIDs(ids...)
	return _c
}

// AddFavoriteOfUser adds the "favorite_of_user" edges to the User entity.
func (_c *TagCreate) AddFavoriteOfUser(v ...*User) *TagCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFavoriteOfUserIDs(ids...)
}

// Mutation returns the TagMutation object of the builder.
func (_c *TagCreate) Mutation() *TagMutation {
	return _c.mutation
}

// Save creates the Tag in the database.
func (_c *TagCreate) Save(ctx context.Context) (*Tag, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TagCreate) SaveX(ctx context.Context) *Tag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TagCreate) defaults() {
	if _, ok := _c.mutation.Favorite(); !ok {
		v := tag.DefaultFavorite
		_c.mutation.SetFavorite(v)
	}
	if _, ok := _c.mutation.Hidden(); !ok {
		v := tag.DefaultHidden
		_c.mutation.SetHidden(v)
	}
	if _, ok := _c.mutation.LastUpdate(); !ok {
		v := tag.DefaultLastUpdate
		_c.mutation.SetLastUpdate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TagCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tag.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := tag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tag.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Favorite(); !ok {
		return &ValidationError{Name: "favorite", err: errors.New(`ent: missing required field "Tag.favorite"`)}
	}
	if _, ok := _c.mutation.Hidden(); !ok {
		return &ValidationError{Name: "hidden", err: errors.New(`ent: missing required field "Tag.hidden"`)}
	}
	return nil
}

func (_c *TagCreate) sqlSave(ctx context.Context) (*Tag, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TagCreate) createSpec() (*Tag, *sqlgraph.CreateSpec) {
	var (
		_node = &Tag{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tag.Table, sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tag.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Favorite(); ok {
		_spec.SetField(tag.FieldFavorite, field.TypeBool, value)
		_node.Favorite = value
	}
	if value, ok := _c.mutation.Hidden(); ok {
		_spec.SetField(tag.FieldHidden, field.TypeBool, value)
		_node.Hidden = value
	}
	if value, ok := _c.mutation.LastUpdate(); ok {
		_spec.SetField(tag.FieldLastUpdate, field.TypeTime, value)
		_node.LastUpdate = value
	}
	if nodes := _c.mutation.MetaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.MetaTable,
			Columns: tag.MetaPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FavoriteOfUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.FavoriteOfUserTable,
			Columns: tag.FavoriteOfUserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Tag.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TagUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *TagCreate) OnConflict(opts ...sql.ConflictOption) *TagUpsertOne {
	_c.conflict = opts
	return &TagUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Tag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TagCreate) OnConflictColumns(columns ...string) *TagUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TagUpsertOne{
		create: _c,
	}
}

type (
	// TagUpsertOne is the builder for "upsert"-ing
	//  one Tag node.
	TagUpsertOne struct {
		create *TagCreate
	}

	// TagUpsert is the "OnConflict" setter.
	TagUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *TagUpsert) SetName(v string) *TagUpsert {
	u.Set(tag.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TagUpsert) UpdateName() *TagUpsert {
	u.SetExcluded(tag.FieldName)
	return u
}

// SetFavorite sets the "favorite" field.
func (u *TagUpsert) SetFavorite(v bool) *TagUpsert {
	u.Set(tag.FieldFavorite, v)
	return u
}

// UpdateFavorite sets the "favorite" field to the value that was provided on create.
func (u *TagUpsert) UpdateFavorite() *TagUpsert {
	u.SetExcluded(tag.FieldFavorite)
	return u
}

// SetHidden sets the "hidden" field.
func (u *TagUpsert) SetHidden(v bool) *TagUpsert {
	u.Set(tag.FieldHidden, v)
	return u
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *TagUpsert) UpdateHidden() *TagUpsert {
	u.SetExcluded(tag.FieldHidden)
	return u
}

// SetLastUpdate sets the "last_update" field.
func (u *TagUpsert) SetLastUpdate(v time.Time) *TagUpsert {
	u.Set(tag.FieldLastUpdate, v)
	return u
}

// UpdateLastUpdate sets the "last_update" field to the value that was provided on create.
func (u *TagUpsert) UpdateLastUpdate() *TagUpsert {
	u.SetExcluded(tag.FieldLastUpdate)
	return u
}

// ClearLastUpdate clears the value of the "last_update" field.
func (u *TagUpsert) ClearLastUpdate() *TagUpsert {
	u.SetNull(tag.FieldLastUpdate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Tag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TagUpsertOne) UpdateNewValues() *TagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Tag.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TagUpsertOne) Ignore() *TagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TagUpsertOne) DoNothing() *TagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TagCreate.OnConflict
// documentation for more info.
func (u *TagUpsertOne) Update(set func(*TagUpsert)) *TagUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TagUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TagUpsertOne) SetName(v string) *TagUpsertOne {
	return u.Update(func(s *TagUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TagUpsertOne) UpdateName() *TagUpsertOne {
	return u.Update(func(s *TagUpsert) {
		s.UpdateName()
	})
}

// SetFavorite sets the "favorite" field.
func (u *TagUpsertOne) SetFavorite(v bool) *TagUpsertOne {
	return u.Update(func(s *TagUpsert) {
		s.SetFavorite(v)
	})
}

// UpdateFavorite sets the "favorite" field to the value that was provided on create.
func (u *TagUpsertOne) UpdateFavorite() *TagUpsertOne {
	return u.Update(func(s *TagUpsert) {
		s.UpdateFavorite()
	})
}

// SetHidden sets the "hidden" field.
func (u *TagUpsertOne) SetHidden(v bool) *TagUpsertOne {
	return u.Update(func(s *TagUpsert) {
		s.SetHidden(v)
	})
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *TagUpsertOne) UpdateHidden() *TagUpsertOne {
	return u.Update(func(s *TagUpsert) {
		s.UpdateHidden()
	})
}

// SetLastUpdate sets the "last_update" field.
func (u *TagUpsertOne) SetLastUpdate(v time.Time) *TagUpsertOne {
	return u.Update(func(s *TagUpsert) {
		s.SetLastUpdate(v)
	})
}

// UpdateLastUpdate sets the "last_update" field to the value that was provided on create.
func (u *TagUpsertOne) UpdateLastUpdate() *TagUpsertOne {
	return u.Update(func(s *TagUpsert) {
		s.UpdateLastUpdate()
	})
}

// ClearLastUpdate clears the value of the "last_update" field.
func (u *TagUpsertOne) ClearLastUpdate() *TagUpsertOne {
	return u.Update(func(s *TagUpsert) {
		s.ClearLastUpdate()
	})
}

// Exec executes the query.
func (u *TagUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TagCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TagUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TagUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TagUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TagCreateBulk is the builder for creating many Tag entities in bulk.
type TagCreateBulk struct {
	config
	err      error
	builders []*TagCreate
	conflict []sql.ConflictOption
}

// Save creates the Tag entities in the database.
func (_c *TagCreateBulk) Save(ctx context.Context) ([]*Tag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Tag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TagCreateBulk) SaveX(ctx context.Context) []*Tag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Tag.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TagUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *TagCreateBulk) OnConflict(opts ...sql.ConflictOption) *TagUpsertBulk {
	_c.conflict = opts
	return &TagUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Tag.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TagCreateBulk) OnConflictColumns(columns ...string) *TagUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TagUpsertBulk{
		create: _c,
	}
}

// TagUpsertBulk is the builder for "upsert"-ing
// a bulk of Tag nodes.
type TagUpsertBulk struct {
	create *TagCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Tag.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TagUpsertBulk) UpdateNewValues() *TagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Tag.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TagUpsertBulk) Ignore() *TagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TagUpsertBulk) DoNothing() *TagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TagCreateBulk.OnConflict
// documentation for more info.
func (u *TagUpsertBulk) Update(set func(*TagUpsert)) *TagUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TagUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TagUpsertBulk) SetName(v string) *TagUpsertBulk {
	return u.Update(func(s *TagUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TagUpsertBulk) UpdateName() *TagUpsertBulk {
	return u.Update(func(s *TagUpsert) {
		s.UpdateName()
	})
}

// SetFavorite sets the "favorite" field.
func (u *TagUpsertBulk) SetFavorite(v bool) *TagUpsertBulk {
	return u.Update(func(s *TagUpsert) {
		s.SetFavorite(v)
	})
}

// UpdateFavorite sets the "favorite" field to the value that was provided on create.
func (u *TagUpsertBulk) UpdateFavorite() *TagUpsertBulk {
	return u.Update(func(s *TagUpsert) {
		s.UpdateFavorite()
	})
}

// SetHidden sets the "hidden" field.
func (u *TagUpsertBulk) SetHidden(v bool) *TagUpsertBulk {
	return u.Update(func(s *TagUpsert) {
		s.SetHidden(v)
	})
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *TagUpsertBulk) UpdateHidden() *TagUpsertBulk {
	return u.Update(func(s *TagUpsert) {
		s.UpdateHidden()
	})
}

// SetLastUpdate sets the "last_update" field.
func (u *TagUpsertBulk) SetLastUpdate(v time.Time) *TagUpsertBulk {
	return u.Update(func(s *TagUpsert) {
		s.SetLastUpdate(v)
	})
}

// UpdateLastUpdate sets the "last_update" field to the value that was provided on create.
func (u *TagUpsertBulk) UpdateLastUpdate() *TagUpsertBulk {
	return u.Update(func(s *TagUpsert) {
		s.UpdateLastUpdate()
	})
}

// ClearLastUpdate clears the value of the "last_update" field.
func (u *TagUpsertBulk) ClearLastUpdate() *TagUpsertBulk {
	return u.Update(func(s *TagUpsert) {
		s.ClearLastUpdate()
	})
}

// Exec executes the query.
func (u *TagUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TagCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TagCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TagUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
