// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mangaweb4/mangaweb4-backend/ent/history"
	"github.com/mangaweb4/mangaweb4-backend/ent/meta"
	"github.com/mangaweb4/mangaweb4-backend/ent/predicate"
	"github.com/mangaweb4/mangaweb4-backend/ent/progress"
	"github.com/mangaweb4/mangaweb4-backend/ent/tag"
	"github.com/mangaweb4/mangaweb4-backend/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *UserUpdate) SetActive(v bool) *UserUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *UserUpdate) SetNillableActive(v *bool) *UserUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// AddFavoriteItemIDs adds the "favorite_items" edge to the Meta entity by IDs.
func (_u *UserUpdate) AddFavoriteItemIDs(ids ...int) *UserUpdate {
	_u.mutation.AddFavoriteItemIDs(ids...)
	return _u
}

// AddFavoriteItems adds the "favorite_items" edges to the Meta entity.
func (_u *UserUpdate) AddFavoriteItems(v ...*Meta) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFavoriteItemIDs(ids...)
}

// AddFavoriteTagIDs adds the "favorite_tags" edge to the Tag entity by IDs.
func (_u *UserUpdate) AddFavoriteTagIDs(ids ...int) *UserUpdate {
	_u.mutation.AddFavoriteTagIDs(ids...)
	return _u
}

// AddFavoriteTags adds the "favorite_tags" edges to the Tag entity.
func (_u *UserUpdate) AddFavoriteTags(v ...*Tag) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFavoriteTagIDs(ids...)
}

// AddHistoryIDs adds the "histories" edge to the History entity by IDs.
func (_u *UserUpdate) AddHistoryIDs(ids ...int) *UserUpdate {
	_u.mutation.AddHistoryIDs(ids...)
	return _u
}

// AddHistories adds the "histories" edges to the History entity.
func (_u *UserUpdate) AddHistories(v ...*History) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHistoryIDs(ids...)
}

// AddProgresIDs adds the "progress" edge to the Progress entity by IDs.
func (_u *UserUpdate) AddProgresIDs(ids ...int) *UserUpdate {
	_u.mutation.AddProgresIDs(ids...)
	return _u
}

// AddProgress adds the "progress" edges to the Progress entity.
func (_u *UserUpdate) AddProgress(v ...*Progress) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProgresIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearFavoriteItems clears all "favorite_items" edges to the Meta entity.
func (_u *UserUpdate) ClearFavoriteItems() *UserUpdate {
	_u.mutation.ClearFavoriteItems()
	return _u
}

// RemoveFavoriteItemIDs removes the "favorite_items" edge to Meta entities by IDs.
func (_u *UserUpdate) RemoveFavoriteItemIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveFavoriteItemIDs(ids...)
	return _u
}

// RemoveFavoriteItems removes "favorite_items" edges to Meta entities.
func (_u *UserUpdate) RemoveFavoriteItems(v ...*Meta) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFavoriteItemIDs(ids...)
}

// ClearFavoriteTags clears all "favorite_tags" edges to the Tag entity.
func (_u *UserUpdate) ClearFavoriteTags() *UserUpdate {
	_u.mutation.ClearFavoriteTags()
	return _u
}

// RemoveFavoriteTagIDs removes the "favorite_tags" edge to Tag entities by IDs.
func (_u *UserUpdate) RemoveFavoriteTagIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveFavoriteTagIDs(ids...)
	return _u
}

// RemoveFavoriteTags removes "favorite_tags" edges to Tag entities.
func (_u *UserUpdate) RemoveFavoriteTags(v ...*Tag) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFavoriteTagIDs(ids...)
}

// ClearHistories clears all "histories" edges to the History entity.
func (_u *UserUpdate) ClearHistories() *UserUpdate {
	_u.mutation.ClearHistories()
	return _u
}

// RemoveHistoryIDs removes the "histories" edge to History entities by IDs.
func (_u *UserUpdate) RemoveHistoryIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveHistoryIDs(ids...)
	return _u
}

// RemoveHistories removes "histories" edges to History entities.
func (_u *UserUpdate) RemoveHistories(v ...*History) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHistoryIDs(ids...)
}

// ClearProgress clears all "progress" edges to the Progress entity.
func (_u *UserUpdate) ClearProgress() *UserUpdate {
	_u.mutation.ClearProgress()
	return _u
}

// RemoveProgresIDs removes the "progress" edge to Progress entities by IDs.
func (_u *UserUpdate) RemoveProgresIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveProgresIDs(ids...)
	return _u
}

// RemoveProgress removes "progress" edges to Progress entities.
func (_u *UserUpdate) RemoveProgress(v ...*Progress) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProgresIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(user.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.FavoriteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteItemsTable,
			Columns: user.FavoriteItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFavoriteItemsIDs(); len(nodes) > 0 && !_u.mutation.FavoriteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteItemsTable,
			Columns: user.FavoriteItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FavoriteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteItemsTable,
			Columns: user.FavoriteItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FavoriteTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteTagsTable,
			Columns: user.FavoriteTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFavoriteTagsIDs(); len(nodes) > 0 && !_u.mutation.FavoriteTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteTagsTable,
			Columns: user.FavoriteTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FavoriteTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteTagsTable,
			Columns: user.FavoriteTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HistoriesTable,
			Columns: []string{user.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHistoriesIDs(); len(nodes) > 0 && !_u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HistoriesTable,
			Columns: []string{user.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HistoriesTable,
			Columns: []string{user.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProgressTable,
			Columns: []string{user.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProgressIDs(); len(nodes) > 0 && !_u.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProgressTable,
			Columns: []string{user.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProgressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProgressTable,
			Columns: []string{user.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *UserUpdateOne) SetActive(v bool) *UserUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableActive(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// AddFavoriteItemIDs adds the "favorite_items" edge to the Meta entity by IDs.
func (_u *UserUpdateOne) AddFavoriteItemIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddFavoriteItemIDs(ids...)
	return _u
}

// AddFavoriteItems adds the "favorite_items" edges to the Meta entity.
func (_u *UserUpdateOne) AddFavoriteItems(v ...*Meta) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFavoriteItemIDs(ids...)
}

// AddFavoriteTagIDs adds the "favorite_tags" edge to the Tag entity by IDs.
func (_u *UserUpdateOne) AddFavoriteTagIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddFavoriteTagIDs(ids...)
	return _u
}

// AddFavoriteTags adds the "favorite_tags" edges to the Tag entity.
func (_u *UserUpdateOne) AddFavoriteTags(v ...*Tag) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFavoriteTagIDs(ids...)
}

// AddHistoryIDs adds the "histories" edge to the History entity by IDs.
func (_u *UserUpdateOne) AddHistoryIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddHistoryIDs(ids...)
	return _u
}

// AddHistories adds the "histories" edges to the History entity.
func (_u *UserUpdateOne) AddHistories(v ...*History) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHistoryIDs(ids...)
}

// AddProgresIDs adds the "progress" edge to the Progress entity by IDs.
func (_u *UserUpdateOne) AddProgresIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddProgresIDs(ids...)
	return _u
}

// AddProgress adds the "progress" edges to the Progress entity.
func (_u *UserUpdateOne) AddProgress(v ...*Progress) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProgresIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearFavoriteItems clears all "favorite_items" edges to the Meta entity.
func (_u *UserUpdateOne) ClearFavoriteItems() *UserUpdateOne {
	_u.mutation.ClearFavoriteItems()
	return _u
}

// RemoveFavoriteItemIDs removes the "favorite_items" edge to Meta entities by IDs.
func (_u *UserUpdateOne) RemoveFavoriteItemIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveFavoriteItemIDs(ids...)
	return _u
}

// RemoveFavoriteItems removes "favorite_items" edges to Meta entities.
func (_u *UserUpdateOne) RemoveFavoriteItems(v ...*Meta) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFavoriteItemIDs(ids...)
}

// ClearFavoriteTags clears all "favorite_tags" edges to the Tag entity.
func (_u *UserUpdateOne) ClearFavoriteTags() *UserUpdateOne {
	_u.mutation.ClearFavoriteTags()
	return _u
}

// RemoveFavoriteTagIDs removes the "favorite_tags" edge to Tag entities by IDs.
func (_u *UserUpdateOne) RemoveFavoriteTagIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveFavoriteTagIDs(ids...)
	return _u
}

// RemoveFavoriteTags removes "favorite_tags" edges to Tag entities.
func (_u *UserUpdateOne) RemoveFavoriteTags(v ...*Tag) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFavoriteTagIDs(ids...)
}

// ClearHistories clears all "histories" edges to the History entity.
func (_u *UserUpdateOne) ClearHistories() *UserUpdateOne {
	_u.mutation.ClearHistories()
	return _u
}

// RemoveHistoryIDs removes the "histories" edge to History entities by IDs.
func (_u *UserUpdateOne) RemoveHistoryIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveHistoryIDs(ids...)
	return _u
}

// RemoveHistories removes "histories" edges to History entities.
func (_u *UserUpdateOne) RemoveHistories(v ...*History) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHistoryIDs(ids...)
}

// ClearProgress clears all "progress" edges to the Progress entity.
func (_u *UserUpdateOne) ClearProgress() *UserUpdateOne {
	_u.mutation.ClearProgress()
	return _u
}

// RemoveProgresIDs removes the "progress" edge to Progress entities by IDs.
func (_u *UserUpdateOne) RemoveProgresIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveProgresIDs(ids...)
	return _u
}

// RemoveProgress removes "progress" edges to Progress entities.
func (_u *UserUpdateOne) RemoveProgress(v ...*Progress) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProgresIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(user.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.FavoriteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteItemsTable,
			Columns: user.FavoriteItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFavoriteItemsIDs(); len(nodes) > 0 && !_u.mutation.FavoriteItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteItemsTable,
			Columns: user.FavoriteItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FavoriteItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteItemsTable,
			Columns: user.FavoriteItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(meta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FavoriteTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteTagsTable,
			Columns: user.FavoriteTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFavoriteTagsIDs(); len(nodes) > 0 && !_u.mutation.FavoriteTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteTagsTable,
			Columns: user.FavoriteTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FavoriteTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.FavoriteTagsTable,
			Columns: user.FavoriteTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HistoriesTable,
			Columns: []string{user.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHistoriesIDs(); len(nodes) > 0 && !_u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HistoriesTable,
			Columns: []string{user.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HistoriesTable,
			Columns: []string{user.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProgressTable,
			Columns: []string{user.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProgressIDs(); len(nodes) > 0 && !_u.mutation.ProgressCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProgressTable,
			Columns: []string{user.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProgressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProgressTable,
			Columns: []string{user.ProgressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(progress.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
