// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "maintenance.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Maintenance } from "./maintenance";
import type { MaintenancePopulateTagsResponse } from "./maintenance";
import type { MaintenancePopulateTagsRequest } from "./maintenance";
import type { MaintenanceUpdateLibraryResponse } from "./maintenance";
import type { MaintenanceUpdateLibraryRequest } from "./maintenance";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { MaintenancePurgeCacheResponse } from "./maintenance";
import type { MaintenancePurgeCacheRequest } from "./maintenance";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service Maintenance
 */
export interface IMaintenanceClient {
    /**
     * @generated from protobuf rpc: PurgeCache
     */
    purgeCache(input: MaintenancePurgeCacheRequest, options?: RpcOptions): UnaryCall<MaintenancePurgeCacheRequest, MaintenancePurgeCacheResponse>;
    /**
     * @generated from protobuf rpc: UpdateLibrary
     */
    updateLibrary(input: MaintenanceUpdateLibraryRequest, options?: RpcOptions): UnaryCall<MaintenanceUpdateLibraryRequest, MaintenanceUpdateLibraryResponse>;
    /**
     * @generated from protobuf rpc: PopulateTags
     */
    populateTags(input: MaintenancePopulateTagsRequest, options?: RpcOptions): UnaryCall<MaintenancePopulateTagsRequest, MaintenancePopulateTagsResponse>;
}
/**
 * @generated from protobuf service Maintenance
 */
export class MaintenanceClient implements IMaintenanceClient, ServiceInfo {
    typeName = Maintenance.typeName;
    methods = Maintenance.methods;
    options = Maintenance.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: PurgeCache
     */
    purgeCache(input: MaintenancePurgeCacheRequest, options?: RpcOptions): UnaryCall<MaintenancePurgeCacheRequest, MaintenancePurgeCacheResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<MaintenancePurgeCacheRequest, MaintenancePurgeCacheResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateLibrary
     */
    updateLibrary(input: MaintenanceUpdateLibraryRequest, options?: RpcOptions): UnaryCall<MaintenanceUpdateLibraryRequest, MaintenanceUpdateLibraryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<MaintenanceUpdateLibraryRequest, MaintenanceUpdateLibraryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PopulateTags
     */
    populateTags(input: MaintenancePopulateTagsRequest, options?: RpcOptions): UnaryCall<MaintenancePopulateTagsRequest, MaintenancePopulateTagsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<MaintenancePopulateTagsRequest, MaintenancePopulateTagsResponse>("unary", this._transport, method, opt, input);
    }
}
