// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "system.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { System } from "./system";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SystemInfoResponse } from "./system";
import type { SystemInfoRequest } from "./system";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service System
 */
export interface ISystemClient {
    /**
     * @generated from protobuf rpc: Info
     */
    info(input: SystemInfoRequest, options?: RpcOptions): UnaryCall<SystemInfoRequest, SystemInfoResponse>;
}
/**
 * @generated from protobuf service System
 */
export class SystemClient implements ISystemClient, ServiceInfo {
    typeName = System.typeName;
    methods = System.methods;
    options = System.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Info
     */
    info(input: SystemInfoRequest, options?: RpcOptions): UnaryCall<SystemInfoRequest, SystemInfoResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SystemInfoRequest, SystemInfoResponse>("unary", this._transport, method, opt, input);
    }
}
