// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "tag.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Tag } from "./tag";
import type { TagSetFavoriteResponse } from "./tag";
import type { TagSetFavoriteRequest } from "./tag";
import type { TagThumbnailResponse } from "./tag";
import type { TagThumbnailRequest } from "./tag";
import type { TagDetailResponse } from "./tag";
import type { TagDetailRequest } from "./tag";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { TagListResponse } from "./tag";
import type { TagListRequest } from "./tag";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service Tag
 */
export interface ITagClient {
    /**
     * @generated from protobuf rpc: List
     */
    list(input: TagListRequest, options?: RpcOptions): UnaryCall<TagListRequest, TagListResponse>;
    /**
     * @generated from protobuf rpc: Detail
     */
    detail(input: TagDetailRequest, options?: RpcOptions): UnaryCall<TagDetailRequest, TagDetailResponse>;
    /**
     * @generated from protobuf rpc: Thumbnail
     */
    thumbnail(input: TagThumbnailRequest, options?: RpcOptions): UnaryCall<TagThumbnailRequest, TagThumbnailResponse>;
    /**
     * @generated from protobuf rpc: SetFavorite
     */
    setFavorite(input: TagSetFavoriteRequest, options?: RpcOptions): UnaryCall<TagSetFavoriteRequest, TagSetFavoriteResponse>;
}
/**
 * @generated from protobuf service Tag
 */
export class TagClient implements ITagClient, ServiceInfo {
    typeName = Tag.typeName;
    methods = Tag.methods;
    options = Tag.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: List
     */
    list(input: TagListRequest, options?: RpcOptions): UnaryCall<TagListRequest, TagListResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<TagListRequest, TagListResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Detail
     */
    detail(input: TagDetailRequest, options?: RpcOptions): UnaryCall<TagDetailRequest, TagDetailResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<TagDetailRequest, TagDetailResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Thumbnail
     */
    thumbnail(input: TagThumbnailRequest, options?: RpcOptions): UnaryCall<TagThumbnailRequest, TagThumbnailResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<TagThumbnailRequest, TagThumbnailResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetFavorite
     */
    setFavorite(input: TagSetFavoriteRequest, options?: RpcOptions): UnaryCall<TagSetFavoriteRequest, TagSetFavoriteResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<TagSetFavoriteRequest, TagSetFavoriteResponse>("unary", this._transport, method, opt, input);
    }
}
