name: build-test

on:
  push:
    branches:
      - main
      - master
    paths:
      - "backend/**"
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: '^1.27'

    - name: install vips
      run: apt install libvips-dev

    - name: Build
      run: go build -v ./...
      working-directory: ./backend

    - name: Test
      run: go test -v ./...
      working-directory: ./backend
